'use server';

import { cookies } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { requireUser } from '@/lib/session';
import { resolveActiveChronicle, getChronicle, getMembership } from '@/lib/chronicles';
import {
  addMessage,
  closeConversation,
  findPendingPeopleDraft,
  getConversation,
  listMessages,
  releasePendingReply,
  resolveDraftCard,
  resolvePeopleCard,
  resumableConversation,
  tryClaimPendingReply,
} from '@/lib/conversations';
import type { Receipt, StoryProposal, UndoAction } from '@/lib/ai/tools';
import { applyStoryEdit, claimChatAssetsForStory } from '@/lib/stories';
import { saveProposalAsStory } from '@/lib/story-save';
import {
  canUserEditPerson,
  deletePerson,
  getPerson,
  removeRelationship,
} from '@/lib/people';
import { applyPeopleChanges } from '@/lib/people-changes';
import { canContribute, type AccessRole } from '@/lib/permissions';
import { buildKey, presignPut } from '@/lib/s3';
import { validateUpload } from '@/lib/uploads';
import { makeContext, respondAndStore } from './respond';
import { buildChatMessages } from './messages';
import type { Msg } from './types';

/** Throw unless the user can contribute to the chronicle (create stories / tree). */
async function assertContributor(chronicleId: string, userId: string) {
  const membership = await getMembership(chronicleId, userId);
  if (!membership) throw new Error('You do not have access to this chronicle.');
  if (!canContribute(membership.accessRole as AccessRole)) {
    throw new Error('You do not have permission to add to this chronicle.');
  }
  return membership;
}

/**
 * A presigned URL the browser uses to PUT an in-chat upload straight to storage.
 * Returns the canonical MIME type to store — `validateUpload` normalizes it, and the
 * signature pins both it and the byte length.
 */
export async function presignUpload(input: {
  kind: 'audio' | 'photo';
  mimeType: string;
  bytes: number;
}): Promise<{ url: string; s3Key: string; mimeType: string }> {
  await requireUser();
  const upload = validateUpload(input.kind, input.mimeType, input.bytes);
  const prefix = input.kind === 'audio' ? 'chat/audio' : 'chat/photos';
  const s3Key = buildKey(prefix, upload.ext);
  const url = await presignPut(s3Key, upload.mimeType, upload.bytes);
  return { url, s3Key, mimeType: upload.mimeType };
}

/** How recently a conversation must have been created for the null-id sync fallback. */
const RECENT_CONVERSATION_MS = 10 * 60 * 1000;

export type SyncChatResult =
  /** The stored, canonical conversation — replaces whatever the client was showing. */
  | { status: 'ok'; conversationId: string; messages: Msg[] }
  /** A reply is being generated by another live request — poll again shortly. */
  | { status: 'pending' }
  /** The missing reply could not be regenerated. */
  | { status: 'failed' }
  /** No such (or no resumable) conversation. */
  | { status: 'gone' };

/**
 * Reconcile a client with the stored conversation after its send request died — mobile
 * browsers kill in-flight fetches when the tab is backgrounded, stranding the chat with
 * a stored user message but no visible reply (and no draft card the reply carried).
 * If the last stored turn is a user message with no reply, the reply is (re)generated
 * here first — unless a live request already holds the generation claim.
 *
 * With a null id (the killed send was the conversation's very first message, so the
 * client never learned the id) the user's resumable conversation is used instead.
 */
export async function syncChat(conversationId: string | null): Promise<SyncChatResult> {
  const user = await requireUser();
  const convo = conversationId
    ? await getConversation(conversationId)
    : await resumableConversation(user.id);
  if (!convo || convo.userId !== user.id) return { status: 'gone' };
  // The null-id fallback may only match a conversation the lost send itself just
  // created. An older resumable thread (e.g. "New chat" whose close request also
  // failed) is unrelated — adopting it would replace the client's fresh chat with it
  // and even regenerate a reply into the wrong conversation.
  if (!conversationId && Date.now() - convo.createdAt.getTime() > RECENT_CONVERSATION_MS) {
    return { status: 'gone' };
  }

  const stored = await listMessages(convo.id);
  const lastTurn = [...stored].reverse().find((m) => m.role === 'user' || m.role === 'assistant');
  if (lastTurn?.role === 'user') {
    if (!(await tryClaimPendingReply(convo.id))) return { status: 'pending' };
    try {
      // Between the read above and winning the claim, the original request may have
      // finished — it stores its reply BEFORE releasing the claim, so a fresh read now
      // says reliably whether the turn is still unanswered. Without this re-check the
      // reply would be generated twice.
      const fresh = [...(await listMessages(convo.id))]
        .reverse()
        .find((m) => m.role === 'user' || m.role === 'assistant');
      if (fresh?.role === 'user') {
        const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
        const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
        const ctx = makeContext(user.id, user.name, active);
        ctx.conversationId = convo.id;
        await respondAndStore(convo.id, ctx, previousChronicleId);
      }
    } catch (err) {
      console.error(`Reply recovery failed for conversation ${convo.id}:`, err);
      return { status: 'failed' };
    } finally {
      await releasePendingReply(convo.id);
    }
  }

  return { status: 'ok', conversationId: convo.id, messages: await buildChatMessages(convo.id) };
}

/**
 * Close the current conversation ("New chat"): it stays stored as history (stories
 * keep linking back to it), but a reload/reopen will start fresh instead of resuming it.
 */
export async function endConversation(conversationId: string): Promise<void> {
  const user = await requireUser();
  const convo = await getConversation(conversationId);
  if (!convo || convo.userId !== user.id) return;
  await closeConversation(conversationId);
}

/** Reverse an applied structural action from a receipt's Undo button. */
export async function undoAction(
  undo: UndoAction,
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await requireUser();

  if (undo.kind === 'person') {
    const person = await getPerson(undo.personId);
    if (!person) return { ok: true }; // already removed — nothing to undo
    if (person.userId) {
      return { ok: false, error: 'This person is linked to an account and cannot be deleted.' };
    }
    if (!(await canUserEditPerson(user.id, undo.personId))) {
      return { ok: false, error: 'You do not have permission to undo this.' };
    }
    await deletePerson(undo.personId);
  } else {
    if (!(await canUserEditPerson(user.id, undo.from))) {
      return { ok: false, error: 'You do not have permission to undo this.' };
    }
    await removeRelationship({ type: undo.relType, personFromId: undo.from, personToId: undo.to });
  }

  revalidatePath('/chronicle');
  return { ok: true };
}

/** Accept a story draft → create a ready story shared into the given chronicle. */
export async function acceptStory(input: {
  conversationId: string;
  chronicleId: string;
  proposal: StoryProposal;
}): Promise<{ storyId: string }> {
  const user = await requireUser();
  await assertContributor(input.chronicleId, user.id);

  // Only trust the conversation id if that conversation belongs to the caller.
  const convo = input.conversationId ? await getConversation(input.conversationId) : null;
  const conversationId = convo && convo.userId === user.id ? convo.id : null;

  const saved = await saveProposalAsStory({
    userId: user.id,
    chronicleId: input.chronicleId,
    proposal: input.proposal,
    conversationId,
  });
  if (saved.alreadySaved) return { storyId: saved.storyId };

  if (conversationId) {
    // The receipt on the note renders as a persistent ✓ chip in the chat.
    const chronicle = await getChronicle(input.chronicleId);
    const receipt: Receipt = {
      label: `Saved "${saved.title}"${chronicle ? ` to ${chronicle.name}` : ''}`,
      detail: 'View story',
      href: `/stories/${saved.storyId}`,
    };
    await resolveDraftCard(conversationId);
    await addMessage(
      conversationId,
      'system',
      `[The user accepted the draft card and saved "${saved.title}" as a story (id ${saved.storyId}). ` +
        'It is already stored — do not draft or save it again.]',
      { receipts: [receipt] },
    );
  }

  revalidatePath('/stories');
  return { storyId: saved.storyId };
}

/** Accept a reviewed story revision → update the existing story in place. */
export async function applyStoryUpdate(input: {
  storyId: string;
  proposal: StoryProposal;
  conversationId?: string | null;
}): Promise<{ storyId: string }> {
  const user = await requireUser();
  const p = input.proposal;
  const result = await applyStoryEdit({
    storyId: input.storyId,
    userId: user.id,
    title: p.title,
    summary: p.summary || null,
    body: p.body,
    eventYear: p.eventYear,
    eventMonth: p.eventMonth ?? null,
    eventDay: p.eventDay ?? null,
    appendSource: p.sourceText ?? null,
  });
  if (!result.ok) throw new Error(result.error);

  // Only write the note if the conversation belongs to the caller.
  const convo = input.conversationId ? await getConversation(input.conversationId) : null;
  if (convo && convo.userId === user.id) {
    // A revision claims the chat's new uploads too — the voice notes and photos the
    // user sent while telling the new details. Without this they stay stranded on the
    // conversation (or get grabbed by the next accepted story).
    await claimChatAssetsForStory(convo.id, input.storyId, user.id);
    const receipt: Receipt = {
      label: `Updated "${p.title}"`,
      detail: 'View story',
      href: `/stories/${input.storyId}`,
    };
    await resolveDraftCard(convo.id);
    await addMessage(
      convo.id,
      'system',
      `[The user accepted the revision card — the story "${p.title}" (id ${input.storyId}) is updated.]`,
      { receipts: [receipt] },
    );
  }

  revalidatePath('/stories');
  revalidatePath(`/stories/${input.storyId}`);
  return { storyId: input.storyId };
}

/** Record that the user discarded a draft card, so the agent doesn't assume it was saved. */
export async function discardStoryDraft(input: {
  conversationId: string;
  title: string;
}): Promise<void> {
  const user = await requireUser();
  const convo = await getConversation(input.conversationId);
  if (!convo || convo.userId !== user.id) return;
  await resolveDraftCard(input.conversationId);
  await addMessage(
    input.conversationId,
    'system',
    `[The user discarded the story draft card "${input.title}" without saving. Do not save it; ` +
      'if they want a story about this later, draft a fresh card.]',
  );
}

/**
 * Apply the newest pending tree-changes card via its own Apply button. Server-
 * authoritative: the changeset comes from the stored message metadata, never from the
 * client, so a tampered request can't smuggle in edits the model never actually staged.
 */
export async function confirmPeopleChanges(input: {
  conversationId: string;
}): Promise<{ receipts: Receipt[]; errors: string[] }> {
  const user = await requireUser();
  const convo = await getConversation(input.conversationId);
  if (!convo || convo.userId !== user.id) throw new Error('Conversation not found');

  const pending = await findPendingPeopleDraft(input.conversationId);
  if (!pending) return { receipts: [], errors: [] }; // already resolved — nothing to do

  const { receipts, errors } = await applyPeopleChanges(pending.draft, user.id);
  await resolvePeopleCard(pending.messageId);

  const applied = receipts.length
    ? `Applied ${receipts.length} change${receipts.length === 1 ? '' : 's'} from the card.`
    : 'Nothing from the card could be applied.';
  const failed = errors.length ? ` ${errors.length} failed: ${errors.join('; ')}` : '';
  await addMessage(input.conversationId, 'system', `[The user tapped Apply on the tree-changes card. ${applied}${failed}]`, {
    receipts,
  });

  revalidatePath('/chronicle');
  return { receipts, errors };
}

/** Discard the newest pending tree-changes card via its own Discard button — nothing is applied. */
export async function discardPeopleChanges(input: { conversationId: string }): Promise<void> {
  const user = await requireUser();
  const convo = await getConversation(input.conversationId);
  if (!convo || convo.userId !== user.id) return;

  const pending = await findPendingPeopleDraft(input.conversationId);
  if (!pending) return;
  await resolvePeopleCard(pending.messageId);
  await addMessage(
    input.conversationId,
    'system',
    '[The user discarded the tree-changes card without applying it. Do not stage those changes ' +
      'again unless they ask.]',
  );
}
