'use server';

import { cookies } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { requireUser } from '@/lib/session';
import { resolveActiveChronicle, getChronicle, getMembership } from '@/lib/chronicles';
import {
  addAttachments,
  addMessage,
  claimPendingReply,
  closeConversation,
  createConversation,
  getConversation,
  listMessages,
  photosByMessage,
  releasePendingReply,
  resolveDraftCard,
  resumableConversation,
  tryClaimPendingReply,
  type AttachmentInput,
} from '@/lib/conversations';
import { runAgent, type ChatTurn } from '@/lib/ai/agent';
import type { Receipt, StoryDraft, StoryProposal, ToolContext, UndoAction } from '@/lib/ai/tools';
import { applyStoryEdit, claimChatAssetsForStory } from '@/lib/stories';
import { saveProposalAsStory } from '@/lib/story-save';
import {
  canUserEditPerson,
  deletePerson,
  getPerson,
  removeRelationship,
} from '@/lib/people';
import { canContribute, type AccessRole } from '@/lib/permissions';
import { buildKey, getObjectBuffer, presignGet, presignPut } from '@/lib/s3';
import { validateUpload } from '@/lib/uploads';
import { transcribeAudio } from '@/lib/ai/groq';
import { enqueueTranscode } from '@/lib/queue';
import { buildChatMessages } from './messages';
import type { Msg } from './types';
import { captureServerEvent } from '@/lib/posthog-server';

/** Throw unless the user can contribute to the chronicle (create stories / tree). */
async function assertContributor(chronicleId: string, userId: string) {
  const membership = await getMembership(chronicleId, userId);
  if (!membership) throw new Error('You do not have access to this chronicle.');
  if (!canContribute(membership.accessRole as AccessRole)) {
    throw new Error('You do not have permission to add to this chronicle.');
  }
  return membership;
}

/**
 * A presigned URL the browser uses to PUT an in-chat upload straight to storage.
 * Returns the canonical MIME type to store — `validateUpload` normalizes it, and the
 * signature pins both it and the byte length.
 */
export async function presignUpload(input: {
  kind: 'audio' | 'photo';
  mimeType: string;
  bytes: number;
}): Promise<{ url: string; s3Key: string; mimeType: string }> {
  await requireUser();
  const upload = validateUpload(input.kind, input.mimeType, input.bytes);
  const prefix = input.kind === 'audio' ? 'chat/audio' : 'chat/photos';
  const s3Key = buildKey(prefix, upload.ext);
  const url = await presignPut(s3Key, upload.mimeType, upload.bytes);
  return { url, s3Key, mimeType: upload.mimeType };
}

/**
 * Attachments arrive from the client, so the key it hands back must be one we just
 * signed for that purpose — not a guess at someone's avatar or another story's photo.
 */
function assertChatUpload(kind: 'audio' | 'photo', s3Key: string) {
  const prefix = kind === 'audio' ? 'chat/audio/' : 'chat/photos/';
  if (!s3Key.startsWith(prefix)) throw new Error('Invalid upload.');
}

export interface SendResult {
  conversationId: string;
  reply: string;
  receipts: Receipt[];
  storyDraft: StoryDraft | null;
}

/** Build the mutable per-turn tool context from the resolved active chronicle. */
function makeContext(
  userId: string,
  userName: string,
  active: { id: string; name: string } | undefined,
): ToolContext {
  const ctx: ToolContext = {
    userId,
    userName,
    conversationId: null,
    activeChronicleId: active?.id ?? null,
    activeChronicleName: active?.name ?? null,
    setActiveChronicle(id, name) {
      ctx.activeChronicleId = id;
      ctx.activeChronicleName = name;
    },
  };
  return ctx;
}

/** Resolve the conversation to use (existing, owned) or create a new one. */
async function resolveConversation(
  conversationId: string | null,
  chronicleId: string | null,
  userId: string,
): Promise<string> {
  if (!conversationId) {
    const convo = await createConversation(userId, chronicleId);
    return convo.id;
  }
  const convo = await getConversation(conversationId);
  if (!convo || convo.userId !== userId) throw new Error('Conversation not found');
  return convo.id;
}

/** Run the agent over the conversation, store its reply, and persist any state changes. */
async function respondAndStore(
  conversationId: string,
  ctx: ToolContext,
  previousChronicleId: string | undefined,
): Promise<SendResult> {
  // The agent loop pings this before each step: a long turn keeps re-asserting its
  // generation claim, so it never goes stale mid-run and gets double-generated by a
  // recovery sync (fire-and-forget — a missed ping only shortens the claim).
  ctx.keepAlive = () => {
    claimPendingReply(conversationId).catch(() => {});
  };
  const stored = await listMessages(conversationId);
  const turns = stored.filter(
    (m) => m.role === 'user' || m.role === 'assistant' || m.role === 'system',
  );
  // Photos ride along as images so the agent can see what the story is about. The URLs
  // are presigned reads the model's provider fetches server-side.
  const photoKeys = await photosByMessage(turns.filter((m) => m.role === 'user').map((m) => m.id));
  const history: ChatTurn[] = await Promise.all(
    turns.map(async (m) => ({
      role: m.role as ChatTurn['role'],
      content: m.content,
      imageUrls: await Promise.all(
        (photoKeys.get(m.id) ?? []).map((p) => presignGet(p.s3Key, p.mimeType)),
      ),
    })),
  );

  const result = await runAgent(history, ctx);
  // Persist receipts and any draft card on the assistant message so the ✓ chips and the
  // reviewable card both survive a reload (a phone backgrounding the PWA, say).
  const metadata =
    result.receipts.length || result.storyDraft
      ? {
          ...(result.receipts.length ? { receipts: result.receipts } : {}),
          ...(result.storyDraft ? { storyDraft: result.storyDraft } : {}),
        }
      : undefined;
  await addMessage(conversationId, 'assistant', result.reply, metadata);
  // Record the draft card as a system event so later turns know it exists and
  // that only the user can act on it (prevents "should I save it?" re-drafts).
  if (result.storyDraft) {
    const draftTitle = result.storyDraft.proposal.title;
    await addMessage(
      conversationId,
      'system',
      `[A story draft card "${draftTitle}" is now showing. Only the user can save or discard it ` +
        'on the card; a note will appear here once they do. Do not draft it again or offer to save it.]',
    );
  }

  // A tool may have created/switched the active chronicle — persist it to the cookie.
  if (ctx.activeChronicleId && ctx.activeChronicleId !== previousChronicleId) {
    (await cookies()).set('activeChronicleId', ctx.activeChronicleId, { path: '/' });
  }
  // Any applied action may have changed the family tree or stories pages.
  if (result.receipts.length) {
    revalidatePath('/chronicle');
    revalidatePath('/stories');
  }

  return {
    conversationId,
    reply: result.reply,
    receipts: result.receipts,
    storyDraft: result.storyDraft,
  };
}

/** How recently a conversation must have been created for the null-id sync fallback. */
const RECENT_CONVERSATION_MS = 10 * 60 * 1000;

export type SyncChatResult =
  /** The stored, canonical conversation — replaces whatever the client was showing. */
  | { status: 'ok'; conversationId: string; messages: Msg[] }
  /** A reply is being generated by another live request — poll again shortly. */
  | { status: 'pending' }
  /** The missing reply could not be regenerated. */
  | { status: 'failed' }
  /** No such (or no resumable) conversation. */
  | { status: 'gone' };

/**
 * Reconcile a client with the stored conversation after its send request died — mobile
 * browsers kill in-flight fetches when the tab is backgrounded, stranding the chat with
 * a stored user message but no visible reply (and no draft card the reply carried).
 * If the last stored turn is a user message with no reply, the reply is (re)generated
 * here first — unless a live request already holds the generation claim.
 *
 * With a null id (the killed send was the conversation's very first message, so the
 * client never learned the id) the user's resumable conversation is used instead.
 */
export async function syncChat(conversationId: string | null): Promise<SyncChatResult> {
  const user = await requireUser();
  const convo = conversationId
    ? await getConversation(conversationId)
    : await resumableConversation(user.id);
  if (!convo || convo.userId !== user.id) return { status: 'gone' };
  // The null-id fallback may only match a conversation the lost send itself just
  // created. An older resumable thread (e.g. "New chat" whose close request also
  // failed) is unrelated — adopting it would replace the client's fresh chat with it
  // and even regenerate a reply into the wrong conversation.
  if (!conversationId && Date.now() - convo.createdAt.getTime() > RECENT_CONVERSATION_MS) {
    return { status: 'gone' };
  }

  const stored = await listMessages(convo.id);
  const lastTurn = [...stored].reverse().find((m) => m.role === 'user' || m.role === 'assistant');
  if (lastTurn?.role === 'user') {
    if (!(await tryClaimPendingReply(convo.id))) return { status: 'pending' };
    try {
      // Between the read above and winning the claim, the original request may have
      // finished — it stores its reply BEFORE releasing the claim, so a fresh read now
      // says reliably whether the turn is still unanswered. Without this re-check the
      // reply would be generated twice.
      const fresh = [...(await listMessages(convo.id))]
        .reverse()
        .find((m) => m.role === 'user' || m.role === 'assistant');
      if (fresh?.role === 'user') {
        const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
        const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
        const ctx = makeContext(user.id, user.name, active);
        ctx.conversationId = convo.id;
        await respondAndStore(convo.id, ctx, previousChronicleId);
      }
    } catch (err) {
      console.error(`Reply recovery failed for conversation ${convo.id}:`, err);
      return { status: 'failed' };
    } finally {
      await releasePendingReply(convo.id);
    }
  }

  return { status: 'ok', conversationId: convo.id, messages: await buildChatMessages(convo.id) };
}

/** Persist the user's message (+ any photos), then run the agent for a reply + actions. */
export async function sendMessage(input: {
  conversationId: string | null;
  text: string;
  attachments?: AttachmentInput[];
}): Promise<SendResult> {
  const user = await requireUser();
  const text = input.text.trim();
  const attachments = input.attachments ?? [];
  // Photos alone are a message — the agent sees them.
  if (!text && attachments.length === 0) throw new Error('Empty message');
  for (const a of attachments) assertChatUpload(a.kind, a.s3Key);

  const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
  const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
  const ctx = makeContext(user.id, user.name, active);

  const conversationId = await resolveConversation(input.conversationId, ctx.activeChronicleId, user.id);
  ctx.conversationId = conversationId;
  // Take the generation claim BEFORE the user turn becomes visible in storage: from
  // that moment a recovery `syncChat` (a backgrounded mobile tab reconnecting) would
  // see an unanswered turn and race this request into a duplicate generation.
  await claimPendingReply(conversationId);
  try {
    const message = await addMessage(conversationId, 'user', text);
    if (attachments.length) await addAttachments(message.id, attachments);
    return await respondAndStore(conversationId, ctx, previousChronicleId);
  } finally {
    await releasePendingReply(conversationId);
  }
}

/** Transcribe an uploaded voice note, store it as the user's message, then run the agent. */
export async function sendVoiceMessage(input: {
  conversationId: string | null;
  s3Key: string;
  mimeType: string;
  bytes?: number | null;
  durationSec?: number | null;
}): Promise<SendResult & { transcript: string }> {
  const user = await requireUser();
  assertChatUpload('audio', input.s3Key);

  let transcript: string;
  try {
    const buffer = await getObjectBuffer(input.s3Key);
    const filename = input.s3Key.split('/').pop() ?? 'audio';
    transcript = await transcribeAudio(buffer, filename, input.mimeType);
  } catch (err) {
    console.error(`Voice transcription failed for ${input.s3Key}:`, err);
    throw new Error("Sorry — I couldn't transcribe that recording. Please try again.");
  }

  const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
  const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
  const ctx = makeContext(user.id, user.name, active);

  const conversationId = await resolveConversation(input.conversationId, ctx.activeChronicleId, user.id);
  ctx.conversationId = conversationId;
  // Claim before the user turn is stored — see sendMessage for why.
  await claimPendingReply(conversationId);
  try {
    const message = await addMessage(conversationId, 'user', transcript);
    await addAttachments(message.id, [
      {
        kind: 'audio',
        s3Key: input.s3Key,
        mimeType: input.mimeType,
        bytes: input.bytes ?? null,
        durationSec: input.durationSec ?? null,
      },
    ]);
    // WebM/Opus recordings are silent on Safari/iOS — re-encode to AAC in the background.
    // (The job checks the stored MIME type and skips anything already playable.)
    try {
      await enqueueTranscode({ s3Key: input.s3Key });
    } catch (err) {
      console.error(`Failed to enqueue transcode for ${input.s3Key}:`, err);
    }

    captureServerEvent(user.id, 'voice_message_sent', {
      duration_sec: input.durationSec ?? null,
    });

    const result = await respondAndStore(conversationId, ctx, previousChronicleId);
    return { ...result, transcript };
  } finally {
    await releasePendingReply(conversationId);
  }
}

/**
 * Close the current conversation ("New chat"): it stays stored as history (stories
 * keep linking back to it), but a reload/reopen will start fresh instead of resuming it.
 */
export async function endConversation(conversationId: string): Promise<void> {
  const user = await requireUser();
  const convo = await getConversation(conversationId);
  if (!convo || convo.userId !== user.id) return;
  await closeConversation(conversationId);
}

/** Reverse an applied structural action from a receipt's Undo button. */
export async function undoAction(
  undo: UndoAction,
): Promise<{ ok: true } | { ok: false; error: string }> {
  const user = await requireUser();

  if (undo.kind === 'person') {
    const person = await getPerson(undo.personId);
    if (!person) return { ok: true }; // already removed — nothing to undo
    if (person.userId) {
      return { ok: false, error: 'This person is linked to an account and cannot be deleted.' };
    }
    if (!(await canUserEditPerson(user.id, undo.personId))) {
      return { ok: false, error: 'You do not have permission to undo this.' };
    }
    await deletePerson(undo.personId);
  } else {
    if (!(await canUserEditPerson(user.id, undo.from))) {
      return { ok: false, error: 'You do not have permission to undo this.' };
    }
    await removeRelationship({ type: undo.relType, personFromId: undo.from, personToId: undo.to });
  }

  revalidatePath('/chronicle');
  return { ok: true };
}

/** Accept a story draft → create a ready story shared into the given chronicle. */
export async function acceptStory(input: {
  conversationId: string;
  chronicleId: string;
  proposal: StoryProposal;
}): Promise<{ storyId: string }> {
  const user = await requireUser();
  await assertContributor(input.chronicleId, user.id);

  // Only trust the conversation id if that conversation belongs to the caller.
  const convo = input.conversationId ? await getConversation(input.conversationId) : null;
  const conversationId = convo && convo.userId === user.id ? convo.id : null;

  const saved = await saveProposalAsStory({
    userId: user.id,
    chronicleId: input.chronicleId,
    proposal: input.proposal,
    conversationId,
  });
  if (saved.alreadySaved) return { storyId: saved.storyId };

  captureServerEvent(user.id, 'story_accepted', {
    story_id: saved.storyId,
    chronicle_id: input.chronicleId,
  });

  if (conversationId) {
    // The receipt on the note renders as a persistent ✓ chip in the chat.
    const chronicle = await getChronicle(input.chronicleId);
    const receipt: Receipt = {
      label: `Saved "${saved.title}"${chronicle ? ` to ${chronicle.name}` : ''}`,
      detail: 'View story',
      href: `/stories/${saved.storyId}`,
    };
    await resolveDraftCard(conversationId);
    await addMessage(
      conversationId,
      'system',
      `[The user accepted the draft card and saved "${saved.title}" as a story (id ${saved.storyId}). ` +
        'It is already stored — do not draft or save it again.]',
      { receipts: [receipt] },
    );
  }

  revalidatePath('/stories');
  return { storyId: saved.storyId };
}

/** Accept a reviewed story revision → update the existing story in place. */
export async function applyStoryUpdate(input: {
  storyId: string;
  proposal: StoryProposal;
  conversationId?: string | null;
}): Promise<{ storyId: string }> {
  const user = await requireUser();
  const p = input.proposal;
  const result = await applyStoryEdit({
    storyId: input.storyId,
    userId: user.id,
    title: p.title,
    summary: p.summary || null,
    body: p.body,
    eventYear: p.eventYear,
    eventMonth: p.eventMonth ?? null,
    eventDay: p.eventDay ?? null,
    appendSource: p.sourceText ?? null,
  });
  if (!result.ok) throw new Error(result.error);

  captureServerEvent(user.id, 'story_updated', { story_id: input.storyId });

  // Only write the note if the conversation belongs to the caller.
  const convo = input.conversationId ? await getConversation(input.conversationId) : null;
  if (convo && convo.userId === user.id) {
    // A revision claims the chat's new uploads too — the voice notes and photos the
    // user sent while telling the new details. Without this they stay stranded on the
    // conversation (or get grabbed by the next accepted story).
    await claimChatAssetsForStory(convo.id, input.storyId, user.id);
    const receipt: Receipt = {
      label: `Updated "${p.title}"`,
      detail: 'View story',
      href: `/stories/${input.storyId}`,
    };
    await resolveDraftCard(convo.id);
    await addMessage(
      convo.id,
      'system',
      `[The user accepted the revision card — the story "${p.title}" (id ${input.storyId}) is updated.]`,
      { receipts: [receipt] },
    );
  }

  revalidatePath('/stories');
  revalidatePath(`/stories/${input.storyId}`);
  return { storyId: input.storyId };
}

/** Record that the user discarded a draft card, so the agent doesn't assume it was saved. */
export async function discardStoryDraft(input: {
  conversationId: string;
  title: string;
}): Promise<void> {
  const user = await requireUser();
  const convo = await getConversation(input.conversationId);
  if (!convo || convo.userId !== user.id) return;
  await resolveDraftCard(input.conversationId);
  await addMessage(
    input.conversationId,
    'system',
    `[The user discarded the story draft card "${input.title}" without saving. Do not save it; ` +
      'if they want a story about this later, draft a fresh card.]',
  );
}
