import { cookies } from 'next/headers';
import { revalidatePath } from 'next/cache';
import { resolveActiveChronicle } from '@/lib/chronicles';
import {
  addAttachments,
  addMessage,
  claimPendingReply,
  createConversation,
  findPendingPeopleDraft,
  getConversation,
  listMessages,
  photosByMessage,
  releasePendingReply,
  supersedePendingPeopleDrafts,
  type AttachmentInput,
} from '@/lib/conversations';
import { runAgent, type AgentEmit, type ChatTurn } from '@/lib/ai/agent';
import type { Receipt, StoryDraft, ToolContext } from '@/lib/ai/tools';
import type { PeopleDraft } from '@/lib/people-changes';
import { getObjectBuffer, presignGet } from '@/lib/s3';
import { transcribeAudio } from '@/lib/ai/groq';
import { enqueueTranscode } from '@/lib/queue';

/**
 * The chat turn pipeline, shared by the streaming route (app/api/chat/stream) and the
 * recovery path (`syncChat` in actions.ts). Not a 'use server' module — these are
 * plain server-side functions, and the streaming route needs to call them with an
 * `emit` the actions layer doesn't have.
 */

export interface SendResult {
  conversationId: string;
  reply: string;
  receipts: Receipt[];
  storyDraft: StoryDraft | null;
  peopleDraft: PeopleDraft | null;
  /** The message carrying `peopleDraft` — Apply/Discard target exactly this card. */
  peopleDraftMessageId: string | null;
  /**
   * Set when a tool created/switched the active chronicle this turn. The STREAMING
   * transport cannot persist the cookie itself — `cookies().set()` after the response
   * has started streaming is a silent no-op — so the client calls the
   * `persistActiveChronicle` action with this id when it sees the result.
   */
  activeChronicleChanged: string | null;
}

/** Build the mutable per-turn tool context from the resolved active chronicle. */
export function makeContext(
  userId: string,
  userName: string,
  active: { id: string; name: string } | undefined,
): ToolContext {
  const ctx: ToolContext = {
    userId,
    userName,
    conversationId: null,
    activeChronicleId: active?.id ?? null,
    activeChronicleName: active?.name ?? null,
    setActiveChronicle(id, name) {
      ctx.activeChronicleId = id;
      ctx.activeChronicleName = name;
    },
  };
  return ctx;
}

/** Resolve the conversation to use (existing, owned) or create a new one. */
async function resolveConversation(
  conversationId: string | null,
  chronicleId: string | null,
  userId: string,
): Promise<string> {
  if (!conversationId) {
    const convo = await createConversation(userId, chronicleId);
    return convo.id;
  }
  const convo = await getConversation(conversationId);
  if (!convo || convo.userId !== userId) throw new Error('Conversation not found');
  return convo.id;
}

/**
 * Attachments arrive from the client, so the key it hands back must be one we just
 * signed for that purpose — not a guess at someone's avatar or another story's photo.
 */
export function assertChatUpload(kind: 'audio' | 'photo', s3Key: string) {
  const prefix = kind === 'audio' ? 'chat/audio/' : 'chat/photos/';
  if (!s3Key.startsWith(prefix)) throw new Error('Invalid upload.');
}

/** Run the agent over the conversation, store its reply, and persist any state changes. */
export async function respondAndStore(
  conversationId: string,
  ctx: ToolContext,
  previousChronicleId: string | undefined,
  emit?: AgentEmit,
): Promise<SendResult> {
  // The agent loop pings this while each model call runs: a long turn keeps
  // re-asserting its generation claim, so it never goes stale mid-run and gets
  // double-generated by a recovery sync (fire-and-forget — a missed ping only
  // shortens the claim).
  ctx.keepAlive = () => {
    claimPendingReply(conversationId).catch(() => {});
  };
  const stored = await listMessages(conversationId);
  const turns = stored.filter(
    (m) => m.role === 'user' || m.role === 'assistant' || m.role === 'system',
  );
  // Photos ride along as images so the agent can see what the story is about. The URLs
  // are presigned reads the model's provider fetches server-side.
  const photoKeys = await photosByMessage(turns.filter((m) => m.role === 'user').map((m) => m.id));
  const history: ChatTurn[] = await Promise.all(
    turns.map(async (m) => ({
      role: m.role as ChatTurn['role'],
      content: m.content,
      imageUrls: await Promise.all(
        (photoKeys.get(m.id) ?? []).map((p) => presignGet(p.s3Key, p.mimeType)),
      ),
    })),
  );

  // Seed the turn with the still-pending card, if any: this turn's staging EXTENDS
  // that changeset (and a fresh, complete card replaces it) instead of silently
  // dropping the not-yet-confirmed changes — the model is told never to re-stage them.
  const pendingCard = await findPendingPeopleDraft(conversationId);
  if (pendingCard) {
    ctx.peopleDraft = { ...pendingCard.draft, changes: [...pendingCard.draft.changes] };
  }
  const seededChanges = pendingCard?.draft.changes.length ?? 0;

  const result = await runAgent(history, ctx, emit);
  // Persist a card only when this turn actually changed the set: same count as the
  // seed means the old card (if any) is untouched and stays the live one — storing it
  // again every turn would litter the chat with duplicates. The confirm/cancel tools
  // null the draft after consuming it, so their turns fall through to "no card" here.
  const draftNow = result.peopleDraft?.changes.length ? result.peopleDraft : null;
  const peopleDraft =
    draftNow &&
    (draftNow.changes.length !== seededChanges ||
      draftNow.chronicleId !== pendingCard?.draft.chronicleId)
      ? draftNow
      : null;
  // The fresh, complete card supersedes the earlier one — only one is ever live.
  if (peopleDraft) await supersedePendingPeopleDrafts(conversationId);
  // Persist receipts and any draft card on the assistant message so the ✓ chips and the
  // reviewable card both survive a reload (a phone backgrounding the PWA, say).
  const metadata =
    result.receipts.length || result.storyDraft || peopleDraft
      ? {
          ...(result.receipts.length ? { receipts: result.receipts } : {}),
          ...(result.storyDraft ? { storyDraft: result.storyDraft } : {}),
          ...(peopleDraft ? { peopleDraft } : {}),
        }
      : undefined;
  const assistantMessage = await addMessage(conversationId, 'assistant', result.reply, metadata);
  // Record the draft card as a system event so later turns know it exists and
  // that only the user can act on it (prevents "should I save it?" re-drafts).
  if (result.storyDraft) {
    const draftTitle = result.storyDraft.proposal.title;
    await addMessage(
      conversationId,
      'system',
      `[A story draft card "${draftTitle}" is now showing. Only the user can save or discard it ` +
        'on the card; a note will appear here once they do. Do not draft it again or offer to save it.]',
    );
  }
  if (peopleDraft) {
    await addMessage(
      conversationId,
      'system',
      `[A tree-changes card with ${peopleDraft.changes.length} staged change` +
        `${peopleDraft.changes.length === 1 ? '' : 's'} is now showing — the COMPLETE set, replacing ` +
        'any earlier card. Only the user can apply or discard it on the card (or say so explicitly ' +
        'in chat); a note will appear here once they do. Nothing has been applied yet — do not claim ' +
        'it has, and do not stage the same changes again.]',
    );
  }

  // A tool may have created/switched the active chronicle — persist it to the cookie.
  // Only effective on the server-action path (syncChat recovery): once a route
  // handler's response is streaming, cookie mutations are silently dropped, so the
  // result also carries the change for the client to persist via persistActiveChronicle.
  const activeChronicleChanged =
    ctx.activeChronicleId && ctx.activeChronicleId !== previousChronicleId
      ? ctx.activeChronicleId
      : null;
  if (activeChronicleChanged) {
    (await cookies()).set('activeChronicleId', activeChronicleChanged, { path: '/' });
  }
  // Same caveat: revalidation queued mid-stream never runs — these fire for the
  // recovery path, while the streaming client refreshes its router cache on receipt
  // of the result (chat-view calls router.refresh()).
  if (result.receipts.length) {
    revalidatePath('/chronicle');
    revalidatePath('/stories');
  }

  return {
    conversationId,
    reply: result.reply,
    receipts: result.receipts,
    storyDraft: result.storyDraft,
    peopleDraft,
    peopleDraftMessageId: peopleDraft ? assistantMessage.id : null,
    activeChronicleChanged,
  };
}

/** Persist the user's message (+ any photos), then run the agent for a reply + actions. */
export async function runTextTurn(
  user: { id: string; name: string },
  input: { conversationId: string | null; text: string; attachments: AttachmentInput[] },
  emit?: AgentEmit,
): Promise<SendResult> {
  const text = input.text.trim();
  // Photos alone are a message — the agent sees them.
  if (!text && input.attachments.length === 0) throw new Error('Empty message');
  for (const a of input.attachments) assertChatUpload(a.kind, a.s3Key);

  const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
  const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
  const ctx = makeContext(user.id, user.name, active);

  const conversationId = await resolveConversation(input.conversationId, ctx.activeChronicleId, user.id);
  ctx.conversationId = conversationId;
  // Take the generation claim BEFORE the user turn becomes visible in storage: from
  // that moment a recovery `syncChat` (a backgrounded mobile tab reconnecting) would
  // see an unanswered turn and race this request into a duplicate generation.
  await claimPendingReply(conversationId);
  try {
    const message = await addMessage(conversationId, 'user', text);
    if (input.attachments.length) await addAttachments(message.id, input.attachments);
    return await respondAndStore(conversationId, ctx, previousChronicleId, emit);
  } finally {
    await releasePendingReply(conversationId);
  }
}

/** Transcribe an uploaded voice note, store it as the user's message, then run the agent.
 *  `onTranscript` fires as soon as the words exist — the streaming client fills the
 *  voice bubble with them while the agent is still thinking. */
export async function runVoiceTurn(
  user: { id: string; name: string },
  input: {
    conversationId: string | null;
    s3Key: string;
    mimeType: string;
    bytes?: number | null;
    durationSec?: number | null;
  },
  emit?: AgentEmit,
  onTranscript?: (transcript: string) => void,
): Promise<SendResult & { transcript: string }> {
  assertChatUpload('audio', input.s3Key);

  let transcript: string;
  try {
    const buffer = await getObjectBuffer(input.s3Key);
    const filename = input.s3Key.split('/').pop() ?? 'audio';
    transcript = await transcribeAudio(buffer, filename, input.mimeType);
  } catch (err) {
    console.error(`Voice transcription failed for ${input.s3Key}:`, err);
    throw new Error("Sorry — I couldn't transcribe that recording. Please try again.");
  }
  onTranscript?.(transcript);

  const previousChronicleId = (await cookies()).get('activeChronicleId')?.value;
  const { active } = await resolveActiveChronicle(user.id, previousChronicleId);
  const ctx = makeContext(user.id, user.name, active);

  const conversationId = await resolveConversation(input.conversationId, ctx.activeChronicleId, user.id);
  ctx.conversationId = conversationId;
  // Claim before the user turn is stored — see runTextTurn for why.
  await claimPendingReply(conversationId);
  try {
    const message = await addMessage(conversationId, 'user', transcript);
    await addAttachments(message.id, [
      {
        kind: 'audio',
        s3Key: input.s3Key,
        mimeType: input.mimeType,
        bytes: input.bytes ?? null,
        durationSec: input.durationSec ?? null,
      },
    ]);
    // WebM/Opus recordings are silent on Safari/iOS — re-encode to AAC in the background.
    // (The job checks the stored MIME type and skips anything already playable.)
    try {
      await enqueueTranscode({ s3Key: input.s3Key });
    } catch (err) {
      console.error(`Failed to enqueue transcode for ${input.s3Key}:`, err);
    }

    const result = await respondAndStore(conversationId, ctx, previousChronicleId, emit);
    return { ...result, transcript };
  } finally {
    await releasePendingReply(conversationId);
  }
}
