import type { z } from 'zod';
import type { PeopleDraft } from '@/lib/people-changes';

/**
 * Tool layer for the chat agent. Each tool is a thin, permission-checked wrapper
 * over an existing `lib/*` domain function. The agent loop (`lib/ai/agent.ts`)
 * gives these to the model as OpenAI function tools; when the model calls one we
 * validate its args with the tool's zod `schema`, run `execute`, and feed the
 * result back. Structural writes return a `receipt` (a UI chip); story drafts
 * return a `storyDraft`, and tree edits stage onto `ctx.peopleDraft` — both render
 * as a reviewable card the client shows instead of applying immediately.
 */

/** A story the assistant has drafted but NOT yet committed — awaits user review. */
export interface StoryProposal {
  kind: 'story';
  title: string;
  summary: string;
  body: string;
  eventYear: number | null;
  /** 1–12; refines eventYear. Optional so draft cards persisted before it existed still accept. */
  eventMonth?: number | null;
  /** 1–31; only meaningful together with eventMonth. */
  eventDay?: number | null;
  people: string[];
  /**
   * The user's own words the draft/revision is based on, verbatim. On accept it becomes
   * (new story) or is appended to (revision) the story's source material (`bodyOriginal`).
   * Optional so draft cards persisted before this field existed still accept.
   */
  sourceText?: string | null;
}

/** A story draft handed to the client for review, bound to its target chronicle. */
export interface StoryDraft {
  proposal: StoryProposal;
  chronicleId: string;
  chronicleName: string;
  /** When set, accepting updates this existing story instead of creating one. */
  updateStoryId?: string;
}

/** How to reverse an applied action — attached to a receipt to power an Undo button. */
export type UndoAction =
  | { kind: 'person'; personId: string }
  | { kind: 'relationship'; relType: 'parent' | 'spouse'; from: string; to: string };

/** A short "✓ did X" chip shown under the assistant's reply for an applied action. */
export interface Receipt {
  label: string;
  detail?: string;
  /** Optional in-app link (e.g. a story or invite URL). */
  href?: string;
  /** If set, the chip offers an Undo button that reverses this action. */
  undo?: UndoAction;
}

/**
 * Per-turn context handed to every tool. `activeChronicleId` is MUTABLE — creating a
 * chronicle mid-turn calls `setActiveChronicle` so later tools in the same turn target it.
 * The server action persists the final value to the `activeChronicleId` cookie.
 */
export interface ToolContext {
  userId: string;
  userName: string;
  /** The conversation this turn belongs to — lets tools claim chat uploads etc. */
  conversationId: string | null;
  activeChronicleId: string | null;
  activeChronicleName: string | null;
  setActiveChronicle(id: string, name: string): void;
  /**
   * Called by the agent loop before each think→act step. Lets the caller refresh its
   * reply-generation claim so a long multi-step turn is never mistaken for a crashed
   * one (and double-generated by a recovery sync). Must not throw.
   */
  keepAlive?: () => void;
  /**
   * MUTABLE collector for this turn's staged tree edits. The five people-mutation
   * tools (lib/ai/tools/people.ts) push onto `changes` instead of writing to the DB;
   * the agent loop reads it back at the end of the turn as `AgentResult.peopleDraft`.
   * `null`/unset until the first tool that needs it creates it (with the active
   * chronicle's id/name); reset to `null` by the agent loop at the start of every turn.
   */
  peopleDraft?: PeopleDraft | null;
}

export type ToolResult =
  | {
      ok: true;
      message: string;
      receipt?: Receipt;
      /** Several receipts at once — only confirm_people_changes needs this today. */
      receipts?: Receipt[];
      storyDraft?: StoryDraft;
    }
  | { ok: false; error: string };

export interface Tool<A = unknown> {
  name: string;
  description: string;
  schema: z.ZodType<A>;
  execute(args: A, ctx: ToolContext): Promise<ToolResult>;
}

/** Helper for tool authors: build a well-typed Tool with inference on the args. */
export function defineTool<A>(tool: Tool<A>): Tool<A> {
  return tool;
}
